In [29]:
from numpy import *
a = [1,2,3]
num_a = array(a)
print(type(num_a))

<class 'numpy.ndarray'>


In [30]:
print(pi)

3.141592653589793


In [31]:
b = [4,5,6]
num_b = array(b)
print(num_a+num_b)
print(sin(pi/3))

[5 7 9]
0.8660254037844386


In [32]:
import numpy as np
print(zeros(5))
c = np.array([[2,3,4],[3,4,5]])
print (c.shape)
print(b[-2:])

[0. 0. 0. 0. 0.]
(2, 3)
[5, 6]


In [33]:
print(np.dot(a,b))

32


In [34]:
print(num_a*num_b)

[ 4 10 18]


In [35]:
import pandas as pd
df =  pd.read_csv('test.csv')

In [36]:
df

uid  runs  avg  sixes
0    1     2    3      4
1    5     6    7      8
2    6     7    8      2

In [37]:
df.describe()

uid      runs       avg     sixes
count  3.000000  3.000000  3.000000  3.000000
mean   4.000000  5.000000  6.000000  4.666667
std    2.645751  2.645751  2.645751  3.055050
min    1.000000  2.000000  3.000000  2.000000
25%    3.000000  4.000000  5.000000  3.000000
50%    5.000000  6.000000  7.000000  4.000000
75%    5.500000  6.500000  7.500000  6.000000
max    6.000000  7.000000  8.000000  8.000000

In [38]:
df.head()

uid  runs  avg  sixes
0    1     2    3      4
1    5     6    7      8
2    6     7    8      2